### ISSUE TITLE
[Rexgen] IndexError: list index out of range

### ISSUE THREAD

**Issue by mufeili** [awslabs/dgl-lifesci#95]
@sparklytopaz I open a new issue since the issue you commented is for a different model. The issues are:
1. `IndexError: list index out of range` encountered when training a WLN on custom reaction data for reaction center prediction.
2. Is there an open source software that converts smiles to reaction smiles/smirks ?

**Comment by mufeili** [comment]
For the first issue, can you try:
1. Install DGL 0.5.2 (you may need to uninstall the old version first)
2. Install DGL-LifeSci from source, i.e.
    ```
    git clone https://github.com/awslabs/dgl-lifesci.git
    cd dgl-lifesci/python
    python setup.py install
    ```
3. In `dgl-lifesci/examples/reaction_prediction/rexgen_direct`, run `python find_reaction_center_train.py --train-path test2.txt --val-path test2validate.txt`.

I manage to complete the training without encountering the error.

For the second issue, have you read the "Adapting to a New Dataset" section in the [example README](https://github.com/awslabs/dgl-lifesci/tree/master/examples/reaction_prediction/rexgen_direct)?

**Comment by sparklytopaz** [comment]
@mufeili This might me a package problem?
So the [README](https://github.com/awslabs/dgl-lifesci#requirements) file says that we need rdkit version 2018 but it shows a error -
![image](https://user-images.githubusercontent.com/31735343/94135730-7ecfb800-fe81-11ea-9fa9-17ccb0075246.png)
It doesnt show this error when i upgrade rdkit to 2020 version.
Also for upgraded rdkit version, though I can import it in python interpreter, when I run find_reaction_center_train.py , i get this error -  
ImportError: cannot import name 'BatchedDGLHeteroGraph' from 'dgl' (/home/anaconda3/envs/dgl/lib/python3.7/site-packages/dgl/__init__.py)
I faced this issue previously as well.
My dependencies are - 
I am in a conda environment
dgl-cuda10.2              0.5.2                    py37_0       dglteam
dgllife                   0.2.5                    py37_0              dglteam
rdkit                     2020.03.6        py37h0c252aa_0    conda-forge

Second issue is I have tried adapting to "new Dataset" section

**Comment by mufeili** [comment]
> @mufeili This might me a package problem?
> So the [README](https://github.com/awslabs/dgl-lifesci#requirements) file says that we need rdkit version 2018 but it shows a error -
> ![image](https://user-images.githubusercontent.com/31735343/94135730-7ecfb800-fe81-11ea-9fa9-17ccb0075246.png)
> It doesnt show this error when i upgrade rdkit to 2020 version.
> Also for upgraded rdkit version, though I can import it in python interpreter, when I run find_reaction_center_train.py , i get this error -
> ImportError: cannot import name 'BatchedDGLHeteroGraph' from 'dgl' (/home/anaconda3/envs/dgl/lib/python3.7/site-packages/dgl/**init**.py)
> I faced this issue previously as well.
> My dependencies are -
> I am in a conda environment
> dgl-cuda10.2 0.5.2 py37_0 dglteam
> dgllife 0.2.5 py37_0 dglteam
> rdkit 2020.03.6 py37h0c252aa_0 conda-forge
> 
> Second issue is I have tried adapting to "new Dataset" section

I don't think you have a correct version for DGL-LifeSci. If you take a look at [`acnn.py in the master branch`](https://github.com/awslabs/dgl-lifesci/blob/master/python/dgllife/model/model_zoo/acnn.py#L15), it no longer imports `BatchedDGLHeteroGraph`. I would recommend:
1. Uninstall dgllife and verify the uninstallation by trying to import it
2. Install dgllife from source with
    ```bash
     git clone https://github.com/awslabs/dgl-lifesci.git
     cd dgl-lifesci/python
     python setup.py install
     ```
     If your repo is not update to date, you may need to perform `git pull` first.

**Comment by mufeili** [comment]
I think this issue is fixed and close it for now. Feel free to reopen it.

**Comment by sparklytopaz** [comment]
![image](https://user-images.githubusercontent.com/31735343/95047496-cd901400-0703-11eb-84b2-cbe9f3fdcf8c.png)
still facing this issue - even though i have all the right versions of dgl , dgllife and rdkit
