### ISSUE TITLE
TF backend support

### ISSUE THREAD

**Issue by popfido** [awslabs/dgl-lifesci#126]
I'm using tensorflow as dgl backend in my local macbook since apple release its Metal-accelerated version of tensorflow. But it seems that the dgl-lifesci does not support tensorflow backend when I import dgllife.

```
In [1]: import dgllife
Using backend: tensorflow
2021-01-05 11:13:59.073796: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-68d2941e7384> in <module>
----> 1 import dgllife

~/anaconda3/envs/main/lib/python3.8/site-packages/dgllife/__init__.py in <module>
      7
      8 from .libinfo import __version__
----> 9 from . import model
     10
     11 try:

~/anaconda3/envs/main/lib/python3.8/site-packages/dgllife/model/__init__.py in <module>
      4 # SPDX-License-Identifier: Apache-2.0
      5
----> 6 from .gnn import *
      7 from .readout import *
      8 from .model_zoo import *

~/anaconda3/envs/main/lib/python3.8/site-packages/dgllife/model/gnn/__init__.py in <module>
      6 # Graph neural networks for updating node representations
      7
----> 8 from .attentivefp import *
      9 from .gat import *
     10 from .gcn import *

~/anaconda3/envs/main/lib/python3.8/site-packages/dgllife/model/gnn/attentivefp.py in <module>
     12 import torch.nn.functional as F
     13
---> 14 from dgl.nn.pytorch import edge_softmax
     15
     16 __all__ = ['AttentiveFPGNN']

ModuleNotFoundError: No module named 'dgl.nn.pytorch'
```

So dgllife currently only support pytorch as backend engine and did not intend to be prepared in 0.3 roadmap?

**Comment by mufeili** [comment]
Yes. Due to limited bandwidth, we do not plan to support TF.

**Comment by danielmanu93** [comment]
I'm using pytorch backend to import dgllife but I get this error "ModuleNotFoundError: No module named 'dgl.nn.functional'". How can I fix this.

![1](https://user-images.githubusercontent.com/67971334/120906389-49858780-c616-11eb-879a-c0b72261d766.jpeg)

**Comment by mufeili** [comment]
> I am having a similar problem. I'm using pytorch backend to import dgllife but I get this error "ModuleNotFoundError: No module named 'dgl.nn.functional'". How can I fix this.
> 
> ![1](https://user-images.githubusercontent.com/67971334/120906389-49858780-c616-11eb-879a-c0b72261d766.jpeg)

You need to update DGL to 0.6.x.

**Comment by danielmanu93** [comment]
After I updated DGL to 0.6.1 using conda, the error has changed to "ImportError: cannot import name 'smiles_to_graph' from 'dgllife.utils' ". Below is the code I'm tryna execute:

![1](https://user-images.githubusercontent.com/67971334/120915865-59778880-c663-11eb-9104-7d1e382d5942.jpeg)

**Comment by mufeili** [comment]
> After I updated DGL to 0.6.1 using conda, the error has changed to "ImportError: cannot import name 'smiles_to_graph' from 'dgllife.utils' " as shown below.
> ![1](https://user-images.githubusercontent.com/67971334/120915915-bc691f80-c663-11eb-8ab2-1f117c84390f.jpeg)
> 
> Below is the code I'm tryna execute:
> ![1](https://user-images.githubusercontent.com/67971334/120915865-59778880-c663-11eb-9104-7d1e382d5942.jpeg)

You need to change `smiles_to_graph` to `smiles_to_bigraph`.

**Comment by danielmanu93** [comment]
Thank you! It worked

**Comment by danielmanu93** [comment]
How do I access only the number of edges in the graph? I used g[1] but I get an error.
Below is how it appear when I print all the graph (g). The second attribute is the number of edges. 

![1](https://user-images.githubusercontent.com/67971334/120959249-918bd380-c716-11eb-8337-e9b8fb4e917d.jpeg)

**Comment by mufeili** [comment]
> How do I access only the number of edges in the graph? I used g[1] but I get an error.
> Below is how it appear when I print the graph (g). The second attribute is the number of edges.
> 
> ![1](https://user-images.githubusercontent.com/67971334/120959249-918bd380-c716-11eb-8337-e9b8fb4e917d.jpeg)

You can use `g.num_edges()`.

**Comment by danielmanu93** [comment]
Hi I'm having this issue with SMILES parse error. I'm trying to generate molecules from smiles with the attached generate function but I get the "SMILES parse error" in the terminal when I call the function. How can I fix this issue?

![1](https://user-images.githubusercontent.com/67971334/121855792-fa43f480-ccb0-11eb-8aae-ba98f8a3d751.jpeg)
![2](https://user-images.githubusercontent.com/67971334/121855797-fca64e80-ccb0-11eb-9793-de9be3924088.jpeg)

**Comment by mufeili** [comment]
> Hi I'm having this issue with SMILES parse error. I'm trying to generate molecules from smiles with the attached generate function but I get the "SMILES parse error" in the terminal when I call the function. How can I fix this issue?
> 
> ![1](https://user-images.githubusercontent.com/67971334/121855792-fa43f480-ccb0-11eb-8aae-ba98f8a3d751.jpeg)
> ![2](https://user-images.githubusercontent.com/67971334/121855797-fca64e80-ccb0-11eb-9793-de9be3924088.jpeg)

These appear to be issues related to RDKit so you should open an issue there. If you have further issues, please open a new thread as they are irrelevant to this thread.
